# Generated by Django 5.2.8 on 2026-02-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_image_alter_car_id_alter_cartype_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='base_price_per_day',
        ),
        migrations.AddField(
            model_name='car',
            name='base_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
